/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TopPickRouteImport } from './routes/top-pick'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecordRouteImport } from './routes/record'
import { Route as MyPicksRouteImport } from './routes/my-picks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as GamesIdRouteImport } from './routes/games.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TopPickRoute = TopPickRouteImport.update({
  id: '/top-pick',
  path: '/top-pick',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPicksRoute = MyPicksRouteImport.update({
  id: '/my-picks',
  path: '/my-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-picks': typeof MyPicksRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-pick': typeof TopPickRoute
  '/verify-email': typeof VerifyEmailRoute
  '/games/$id': typeof GamesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-picks': typeof MyPicksRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-pick': typeof TopPickRoute
  '/verify-email': typeof VerifyEmailRoute
  '/games/$id': typeof GamesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-picks': typeof MyPicksRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/top-pick': typeof TopPickRoute
  '/verify-email': typeof VerifyEmailRoute
  '/games/$id': typeof GamesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/games'
    | '/home'
    | '/login'
    | '/my-picks'
    | '/record'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/top-pick'
    | '/verify-email'
    | '/games/$id'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/games'
    | '/home'
    | '/login'
    | '/my-picks'
    | '/record'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/top-pick'
    | '/verify-email'
    | '/games/$id'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/games'
    | '/home'
    | '/login'
    | '/my-picks'
    | '/record'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/top-pick'
    | '/verify-email'
    | '/games/$id'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MyPicksRoute: typeof MyPicksRoute
  RecordRoute: typeof RecordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TopPickRoute: typeof TopPickRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-pick': {
      id: '/top-pick'
      path: '/top-pick'
      fullPath: '/top-pick'
      preLoaderRoute: typeof TopPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-picks': {
      id: '/my-picks'
      path: '/my-picks'
      fullPath: '/my-picks'
      preLoaderRoute: typeof MyPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesIdRoute: typeof GamesIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIdRoute: GamesIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MyPicksRoute: MyPicksRoute,
  RecordRoute: RecordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TopPickRoute: TopPickRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
